### ISSUE TITLE
I have a few bots so create script to apply your patches

### ISSUE THREAD

**Issue by s3frank** [MadJoker0815/roborock_nologs#1]
```
#!/bin/bash
##
# Stop Cron service and Watchdog
echo "Stopping Cron and Watchdog services..."
service rrwatchdoge stop
service cron stop 

# Copy all the files and overwrite
echo "Copying patched files into place..."
yes | cp -rf patch/. /.

# Make sure things are executable
echo "Setting execution flag on scripts..."
chmod +x /opt/rockrobo/rrlog/logclean.sh
chmod +x /root/check_all
chmod +x /root/check_reboot
chmod +x /usr/bin/logrotate.sh

# Restart all services, sleep for 2 minutes and then issue a reboot
echo "Starting Cron and Watchdog again..."
service cron start
sleep 10 
service rrwatchdoge start

echo "Rebooting in 30 seconds..."
sleep 30
reboot
```

This assumes that all the files you currently have in your repo end up in sub directory called patch and the script (apply_patch.sh in my case) is executed in the working directory.

**Comment by MadJoker0815** [comment]
I'm thinking about a install script doing all work.
I think is this would be the easiest way.

**Comment by MadJoker0815** [comment]
I added a install.sh script, this should be able to make the modifications.
Just load this onto the system and execute it via "sh install.sh" It does not matter where the script is located.

https://github.com/MadJoker0815/roborock_nologs/blob/master/install.sh

**Comment by s3frank** [comment]
Awesome


-FF
